### PR TITLE
configure universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@brandob-rhodes can we get a release with wheels?

**Comment by brandon-rhodes** [comment]
Oh — I thought that adding the file was just going to help you with a task you wanted to perform with the library, I didn't know there were additional steps to take :)

First: could you outline what install trouble you ran into, or what errors you received, from the current mechanism where the library is distributed as a .tar.gz?

**Comment by graingert** [comment]
I need you to run `python3 setup.py sdist bdist_wheel upload` this saves a little bit of time installing the package (which we do every CI build)  so the savings build up, and a fair bit of time auditing packages

**Comment by brandon-rhodes** [comment]
I ran the command — only to realize that it created a version 1.7 wheel that, thanks to commits on master since the original 1.7 release, is asymmetric with the sdist version 1.7.

So I resolved your other issue as an excuse for a 1.8 release and then released both sdist and wheels. Let me know if they work or not!

**Pull request merged**
