### PR TITLE
Remove Python <2.7 from supported versions

### PR DESCRIPTION
**Pull request by and-semakin**
Python interpreters 2.6 and below are not supported because they don't have `print()` function.
We can fix support for Python 2.6 adding `from __future__ import print_function` import, but I don't think that there is a reason to support such an old version. Older versions (2.5 and below) are completely incompatible with Python 3.

Commit that breaks Python 2.6 compatibility: https://github.com/brandon-rhodes/logging_tree/commit/a276a2986cee2d8fba9d0ee790a8baa8ab86cf6f

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
The project `setup.py` explicitly declares support for Python 2.6, and I have not heard reports of the library failing on that Python version, nor on any earlier Python version. What exception did you see when you tried testing it?

**Comment by and-semakin** [comment]
Sorry, I created the PR without actually checking the hypothesis. I've checked all the versions through Python 2.3 and now I understand why it works.

**Comment by brandon-rhodes** [comment]
Thank you for testing it! The `print(only_one_single_value)` trick is very limited, but in the early Python 3 days it proved quite helpful for folks targeting 2.6, so I went ahead and used it here. I figured, for so simple a library, why not keep it compatible with every Python version for which `logging` existed?

**Comment by and-semakin** [comment]
Makes sense. Thanks for the library, by the way!

**Pull request closed without merging**
