### PR TITLE
Adding code to run on Powersystem

### PR DESCRIPTION
**Pull request by genisysram**
Hi
Here is my contribution to your code, its working good on powersystems.

Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Interesting! The behavior of the library does not depend on any binary data, so I suspect the extra tests will be unnecessary, but as this module is hardly ever modified its CI cost is near zero anyway, so I'll go ahead and merge. Is there a project that will now be possible thanks to the extra platform tests?

**Comment by gerrith3** [comment]
This package is actually part of Ubuntu 20.04 - we are trying to ensure that users of the ppc64le distributions have perfect parity with Intel distributions.  We don't know who the specific users are but this is probably a somewhat commonly used package on these distros.

**Comment by brandon-rhodes** [comment]
Thanks for the context! I'll land it, though I note that it sounds like Travis is going away and so the tests likely won't run there anymore.

**Comment by gerrith3** [comment]
@brandon-rhodes Travis isn't going away - it did make some changes to crack down on groups like bitcoin miners, and instituted a broader "credit" system.  You get 10,000 credits now, or about 1,000 minutes per month.  If you are doing open source and you run out, simply head to support.travis-ci.com or email to support@travis-ci.com and request additional credits that account for the minutes you need.

**Pull request merged**
